import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const schema = new Schema({
    symbol: String,
    LastUpdated: Date,
    annualReports: [{
      _id: false,
      fiscalDateEnding: Date,
      reportedCurrency: String,
      totalRevenue: Number,
      totalOperatingExpense: Number,
      costOfRevenue: Number,
      grossProfit: Number,
      ebit: Number,
      netIncome: Number,
      researchAndDevelopment: Number,
      effectOfAccountingCharges: String,
      incomeBeforeTax: Number,
      minorityInterest: Number,
      sellingGeneralAdministrative: Number,
      otherNonOperatingIncome: Number,
      operatingIncome: Number,
      otherOperatingExpense: Number,
      interestExpense: Number,
      taxProvision: Number,
      interestIncome: Number,
      netInterestIncome: Number,
      extraordinaryItems: Number,
      nonRecurring: String,
      otherItems: String,
      incomeTaxExpense: Number,
      totalOtherIncomeExpense: Number,
      discontinuedOperations: Number,
      netIncomeFromContinuingOperations: Number,
      netIncomeApplicableToCommonShares: Number,
      preferredStockAndOtherAdjustments: String
    }, { required: false }],
    quarterlyReports: [{
      _id: false,
      fiscalDateEnding: Date,
      reportedCurrency: String,
      totalRevenue: Number,
      totalOperatingExpense: Number,
      costOfRevenue: Number,
      grossProfit: Number,
      ebit: Number,
      netIncome: Number,
      researchAndDevelopment: Number,
      effectOfAccountingCharges: String,
      incomeBeforeTax: Number,
      minorityInterest: Number,
      sellingGeneralAdministrative: Number,
      otherNonOperatingIncome: Number,
      operatingIncome: Number,
      otherOperatingExpense: Number,
      interestExpense: Number,
      taxProvision: Number,
      interestIncome: Number,
      netInterestIncome: Number,
      extraordinaryItems: Number,
      nonRecurring: String,
      otherItems: String,
      incomeTaxExpense: Number,
      totalOtherIncomeExpense: Number,
      discontinuedOperations: Number,
      netIncomeFromContinuingOperations: Number,
      netIncomeApplicableToCommonShares: Number,
      preferredStockAndOtherAdjustments: String
    }]
})

const finalModel = model('IncomeStatement', schema)

export default finalModel;