import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const schema = new Schema({
    Symbol: String,
    LastUpdated: Date,
    AnnualReports: [{
      _id: false,
      fiscalDateEnding: Date,
      reportedCurrency: String,
      totalAssets: Number,
      intangibleAssets: Number,
      earningAssets: String,
      otherCurrentAssets: Number,
      totalLiabilities: Number,
      totalShareholderEquity: Number,
      deferredLongTermLiabilities: Number,
      otherCurrentLiabilities: Number,
      commonStock: Number,
      retainedEarnings: Number,
      otherLiabilities: Number,
      goodwill: Number,
      otherAssets: Number,
      cash: Number,
      totalCurrentLiabilities: Number,
      shortTermDebt: Number,
      currentLongTermDebt: Number,
      otherShareholderEquity: Number,
      propertyPlantEquipment: Number,
      totalCurrentAssets: Number,
      longTermInvestments: Number,
      netTangibleAssets: Number,
      shortTermInvestments: Number,
      netReceivables: Number,
      longTermDebt: Number,
      inventory: Number,
      accountsPayable: Number,
      totalPermanentEquity: String,
      additionalPaidInCapital: String,
      commonStockTotalEquity: Number,
      preferredStockTotalEquity: String,
      retainedEarningsTotalEquity: Number,
      treasuryStock: Number,
      accumulatedAmortization: String,
      otherNonCurrrentAssets: Number,
      deferredLongTermAssetCharges: String,
      totalNonCurrentAssets: Number,
      capitalLeaseObligations: Number,
      totalLongTermDebt: Number,
      otherNonCurrentLiabilities: Number,
      totalNonCurrentLiabilities: Number,
      negativeGoodwill: String,
      warrants: String,
      preferredStockRedeemable: String,
      capitalSurplus: Number,
      liabilitiesAndShareholderEquity: Number,
      cashAndShortTermInvestments: Number,
      accumulatedDepreciation: Number,
      commonStockSharesOutstanding: Number,
    }, { required: true }],
})

const finalModel = model('BalanceSheet', schema)

export default finalModel;