import mongoose from 'mongoose';
const { Schema, model } = mongoose;

const schema = new Schema({
    Symbol: String,
    LastUpdated: String,
    Name: String,
    Description: String,
    Exchange: String,
    Currency: String,
    Country: String,
    Sector: String,
    Industry: String,
    FullTimeEmployees: Number,
    FiscalYearEnd: String,
    LatestQuarter: String,
    MarketCapitalization: Number,
    EBITDA: Number,
    PERatio: Number,
    PEGRatio: Number,
    BookValue: Number,
    DividendPerShare: Number,
    DividendYield: Number,
    EPS: Number,
    RevenuePerShareTTM: Number,
    ProfitMargin: Number, 
    OperatingMarginTTM: Number, 
    ReturnOnAssetsTTM: Number, 
    ReturnOnEquityTTM: Number,
    RevenueTTM: Number,
    GrossProfitTTM: Number,
    DilutedEPSTTM: Number,
    QuarterlyEarningsGrowthYOY: Number,
    QuarterlyRevenueGrowthYOY: Number,
    AnalystTargetPrice: Number,
    TrailingPE: Number,
    ForwardPE: Number,
    PriceToSalesRatioTTM: Number,
    PriceToBookRatio: Number,
    EVToRevenue: Number,
    EVToEBITDA: Number,
    Beta: Number,
    "52WeekHigh": Number,
    "52WeekLow": Number,
    "50DayMovingAverage": Number,
    "200DayMovingAverage": Number,
    SharesOutstanding: Number,
    SharesFloat: Number,
    SharesShort: Number,
    SharesShortPriorMonth: Number,
    ShortRatio: Number,
    ShortPercentOutstanding: Number,
    ShortPercentFloat: Number,
    PercentInsiders: Number,
    PercentInstitutions: Number,
    ForwardAnnualDividendRate: Number,
    ForwardAnnualDividendYield: Number,
    PayoutRatio: Number,
    DividendDate: String,
    ExDividendDate: String,
    LastSplitFactor: String,
    LastSplitDate: String,
})

const finalModel = model('CompanyOverview', schema)

export default finalModel;